language: python

install:
  - pip install -r requirements.txt -r requirements-dev.txt
  - pip install -e .

stages:
  - name: basic tests
    if: type = push
  - name: behind Earthdata
    if: branch = master OR commit_message =~ nsidc_tests OR type = cron

#ultimately move basic tests list into a separate script with the list of files to run (then this can be put into a matrix and paralellized as well)
jobs:
  include:
    - stage: basic tests
      script: pytest icepyx/tests/test_APIformatting.py
              icepyx/tests/test_geospatial.py
              icepyx/tests/test_is2ref.py
              icepyx/tests/test_validate_inputs.py
      after_success: codecov

    # - stage: behind Earthdata
    #   script: 
    #     - export NSIDC_LOGIN=$NSIDC_LOGIN
    #     - pytest icepyx/tests/behind_NSIDC_API_login.py
